### ISSUE TITLE
Electron Test Builds

### ISSUE THREAD

**Issue by LanceGundersen** [stanglab/playground#5]
Verified compiled builds.

- [x] Windows x64
- [x] Mac OSX
- [x] Linux

**Comment by LanceGundersen** [comment]
I have packaged them all and placed the builds in the shared google [drive](https://drive.google.com/drive/u/0/folders/1J0dUbp1wzWx7m308XPzfTnJh9AEI5Ff8). 

A couple things:
It looked like the icons didn't get imported.
I am not sure the Linux version is "fully" compiled to what the desktop is expecting. Will troubleshoot more.

**Comment by Drbaltar** [comment]
Verified that the Windows x64 version that was posted worked correctly. I did not see any icons in the app, just the buttons. If you want to rebuild with icons for me to test again, just let me know.

**Comment by LanceGundersen** [comment]
Does the .exe have a hard drive icon? Mine actually did but the linux OS didn't render it. I believe it is working properly.

**Comment by LanceGundersen** [comment]
Closing the issue as I have built and tested for all OS's on branch test-builds.
